steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app:v1', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/app:v1']
- name: "gcr.io/cloud-builders/gke-deploy"
  args: 
  - run 
  - --filename=Kubernetes/
  - --location=us-east1-b
  - --cluster=kube1 


