apiVersion: apps/v1
kind: Deployment
metadata:
  name: birdspecies
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: birdspeciesmodel
  template:
    metadata:
      labels:
        app: birdspeciesmodel
    spec: 
      containers: 
      - name: container-app
        image: gcr.io/adroit-outlet-376521/app:v1
        ports:
        - containerPort: 8501