apiVersion: app:v1
kind: Deployment
metadata:
  name: birdspecies
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: birdspecies_model
  template:
    metadata:
      labels:
        app: birdspecies_model
    spec: 
      containers: 
      - name: container-app
        image: gcr.io/adroit-outlet-376521/app:v1
        ports:
        - containerPort: 6080